[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
  'cd BackNtier',
  'dotnet restore Talky_API/Talky_API.csproj',
  'dotnet publish Talky_API/Talky_API.csproj -c Release -o out'
]

[phases.start]
cmd = 'cd BackNtier/out && dotnet Talky_API.dll --urls http://0.0.0.0:$PORT'
